---
title: "module3"
author: "Linwan Xu"
date: "2020/12/2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(jpeg) #get RGB
library(magick) # get images
library(dplyr)
library(OpenImageR) # resize images
library(imager)
library(glmnet)
library(ramify) #for selecting largest prob

Sys.setenv(LANGUAGE = "en")
```


```{r}
img.tr = list.files(path = "./tr", pattern = ".jpg", full.names = T)
img.te = list.files(path = "./te", pattern = ".jpg", full.names = T)

train.img = lapply(img.tr, load.image)
test.img = lapply(img.te, load.image)
#allInfo = image_info(image_read(img))

#allInfo$fileName = list.files(path = "./tr", pattern = ".jpg")

categories = c("cardboard", "glass", "metal", "paper", "plastic", "landfill trash")

folder = "./tr"
y.tr.file = list.files(path = folder, pattern = ".txt")
y.tr= c(rep(data.frame(), length(y.tr.file)))

for(i in 1:length(y.tr.file)) 
{
  y.tr[i] = data.frame(read.table(file.path(folder, y.tr.file[i])))
} 

y.train = data.frame("Id" = 1:length(y.tr.file))
y.tr.df = data.frame(matrix(unlist(y.tr), nrow=length(y.tr), byrow=T))
colnames(y.tr.df) = "y"
y.train$y = y.tr.df$y
head(y.train)
```



```{r}
# convert rgb to greyscale
grey.train = train.img
grey.test = test.img

for (i in 1:length(train.img)){
  grey.train[[i]] = grayscale(train.img[[i]], method = "Luma", drop = TRUE)
}

for (i in 1:length(test.img))
{
  grey.test[[i]] = grayscale(test.img[[i]], method = "Luma", drop = TRUE)
}
```



```{r}
#resize all the images
grey.train.re = grey.train
grey.test.re = grey.test

for (i in 1:length(grey.train))
{
  grey.train.re[[i]] = resize(grey.train[[i]], 51, 38)
}
for (i in 1:length(grey.test))
{
  grey.test.re[[i]] = resize(grey.test[[i]], 51, 38)
}
```



```{r}
#numerical dataframe of train set (greyscale)
train.greydf = as.data.frame(rbind(c(grey.train.re[[1]][, , , 1]), c(grey.train.re[[2]][, , , 1])))

for (i in 3:length(grey.train.re))
{
  train.greydf = rbind(train.greydf, c(grey.train.re[[i]][, , , 1]))
}

train.greydf = cbind("y" = y.tr.df$y, train.greydf)
head(train.greydf)
```

```{r}
#numerical dataframe of test set (greyscale)
test.greydf = as.data.frame(rbind(c(grey.test.re[[1]][, , , 1]), c(grey.test.re[[2]][, , , 1])))

for (i in 3:length(grey.test.re))
{
  test.greydf = rbind(test.greydf, c(grey.test.re[[i]][, , , 1]))
}

head(test.greydf)
```



```{r}
n = 500

x.train = train.greydf[-1]
s = sample(1:nrow(x.train), n, replace = FALSE)
x.train = x.train[s ,]
x.train = as.matrix(x.train)

y.train = train.greydf$y
y.train = y.train[s]
y.train = as.factor(y.train)

x.test = test.greydf

fit.lasso = cv.glmnet(x = x.train, y = y.train, alpha=1, family="multinomial")
#yhat = predict(fit.lasso, s=fit.lasso$lambda.1se, newx=x.test)

#yhat
```


```{r}
x.test = as.matrix(x.test)
yhat_prob = predict(fit.lasso, s=fit.lasso$lambda.1se, newx=x.test, type="response")

#yhat_prob
```

```{r}
prediction = argmax(yhat_prob)
#prediction
```


```{r}
kaggle = read.table(file = 'example.csv', sep = ',', header = T, row.names = NULL)
kaggle$Prediction = prediction
write.table(kaggle, file = 'kaggle2.csv', sep = ',', quote = F, row.name = FALSE)
```

